apiVersion: v1
kind: Service
metadata:
  name: apache
  labels:
    name: apache
    app: apache
spec:
  type: NodePort
  ports:
     - port: 80
       targetPort: 80
       nodePort: 42000
       protocol: TCP
  selector:
    app: apache
