apiVersion: apps/v1
kind: Deployment
metadata:
  name: 22051107-svr
  labels:
    app: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: sczw/22051107_webimage
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache
  labels:
    name: apache
    app: apache
spec:
  type: NodePort
  ports:
     - port: 80
       targetPort: 80
       nodePort: 42000
       protocol: TCP
  selector:
    app: apache
