---
version: "3.2"
services:
  apache:
    build: .
    image: koonsingrp/22050108_webimage
    container_name: S2_22050108_Server
    ports:
      - 42000:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
