---
version: "3.2"
services:
  apache:
    build: .
    image: sczw/22051107_webimage
    container_name: 22051107_Server
    ports:
      - 42000:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
